[package]
name = "egui-id-bug"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
env_logger = { version = "0.11.5", default-features = false, features = [
    "auto-color",
    "humantime",
] }